# Generated by Django 4.2.30 on 2026-08-31 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_complainant_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('wing_or_zone', models.CharField(default='Central Campus', max_length=50)),
                ('total_floors', models.PositiveIntegerField(default=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('map_x', models.FloatField(default=50.0, help_text='X position percentage on campus map (0-100)')),
                ('map_y', models.FloatField(default=50.0, help_text='Y position percentage on campus map (0-100)')),
                ('map_width', models.FloatField(default=12.0)),
                ('map_height', models.FloatField(default=10.0)),
                ('building_icon', models.CharField(default='Building2', max_length=50)),
                ('color_accent', models.CharField(default='#3b82f6', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_departments', models.ManyToManyField(blank=True, related_name='buildings', to='complaints.department')),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('projector_av', 'Projector & AV System'), ('workstation_pc', 'Computer / Workstations / OS'), ('ac_cooling', 'Air Conditioning & Ventilation'), ('network_wifi', 'Wi-Fi & LAN Connectivity'), ('electrical_power', 'Power Outlets & Lighting'), ('furniture', 'Chairs, Benches & Whiteboards'), ('lab_equipment', 'Specialized Lab Hardware'), ('cleanliness', 'Housekeeping & Cleanliness'), ('other', 'Other Facility Issue')], default='other', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low (Non-urgent)'), ('medium', 'Medium (Standard)'), ('high', 'High (Affects Lectures)'), ('critical', 'Critical (Immediate Attention)')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Reported / Open'), ('in_progress', 'Technician Assigned / In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('reported_by_name', models.CharField(default='Faculty / Student', max_length=100)),
                ('reported_by_email', models.CharField(blank=True, max_length=100)),
                ('assigned_technician', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('floor_number', models.IntegerField(default=0, help_text='0 for Ground, 1 for 1st floor, etc.')),
                ('room_type', models.CharField(choices=[('smart_classroom', 'Smart Classroom'), ('lecture_hall', 'Lecture Theatre / Hall'), ('computer_lab', 'Computer & Software Lab'), ('ai_gpu_lab', 'AI / High Performance Computing Lab'), ('hardware_lab', 'Electronics & IoT Lab'), ('mechanical_lab', 'Robotics & Mechanical Lab'), ('science_lab', 'Physics / Chemistry Research Lab'), ('seminar_hall', 'Seminar & Conference Hall'), ('auditorium', 'Auditorium')], default='smart_classroom', max_length=30)),
                ('capacity', models.PositiveIntegerField(default=60)),
                ('current_status', models.CharField(choices=[('vacant', 'Vacant / Available'), ('occupied', 'In Session / Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance')], default='vacant', max_length=20)),
                ('current_activity', models.CharField(blank=True, help_text='e.g. CS-301 Operating Systems (Prof. Verma)', max_length=200, null=True)),
                ('current_instructor', models.CharField(blank=True, max_length=100, null=True)),
                ('next_available_time', models.CharField(blank=True, help_text='e.g. Available at 01:15 PM', max_length=100, null=True)),
                ('has_ac', models.BooleanField(default=True)),
                ('has_projector', models.BooleanField(default=True)),
                ('has_smart_board', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_sound_system', models.BooleanField(default=True)),
                ('workstations_count', models.PositiveIntegerField(default=0, help_text='Number of computer terminals if lab')),
                ('power_backup', models.BooleanField(default=True)),
                ('energy_mode_active', models.BooleanField(default=False, help_text='True if room is vacant but lights/AC are running')),
                ('last_status_updated', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='complaints.building')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='complaints.department')),
            ],
            options={
                'ordering': ['building', 'floor_number', 'room_number'],
                'unique_together': {('building', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='RoomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], default='monday', max_length=15)),
                ('start_time', models.CharField(help_text='e.g. 09:00 AM', max_length=10)),
                ('end_time', models.CharField(help_text='e.g. 11:00 AM', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('faculty_name', models.CharField(max_length=100)),
                ('batch_info', models.CharField(blank=True, help_text='e.g. B.Tech CSE Batch A3', max_length=50)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='complaints.room')),
            ],
        ),
        migrations.RemoveField(
            model_name='complaintlog',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaintlog',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='ComplaintLog',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='infrastructureissue',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='complaints.room'),
        ),
    ]
