# Generated by Django 4.2.30 on 2026-08-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_building_infrastructureissue_room_roomschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.FloatField(default=18.5186, help_text='GPS Latitude'),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.FloatField(default=73.8153, help_text='GPS Longitude'),
        ),
    ]
