# Generated by Django 4.2.30 on 2026-09-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_building_latitude_building_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_occupancy',
            field=models.PositiveIntegerField(default=0, help_text='Live count of students present'),
        ),
        migrations.AddField(
            model_name='room',
            name='engagement_score',
            field=models.FloatField(default=0.0, help_text='Live engagement percentage 0-100'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_sensor_update',
            field=models.DateTimeField(blank=True, help_text='Last time real sensor data was received', null=True),
        ),
    ]
