# Generated by Django 4.2.30 on 2026-10-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_room_current_occupancy_room_engagement_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructureissue',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, help_text='Expected deadline for resolving this issue', null=True),
        ),
    ]
